"use client";

import Link from "next/link";
import { Plus } from "lucide-react";
import { useState } from "react";
import type { ResearchStatus, TodayResearchItem } from "@/domain/research";

const sections: { status: ResearchStatus; title: string; tone: string }[] = [{ status: "needs-review", title: "Needs review", tone: "orange" }, { status: "in-research", title: "In research", tone: "blue" }, { status: "awaiting-review", title: "Awaiting review", tone: "purple" }];
const labels: Record<ResearchStatus, string> = { "needs-review": "Needs review", "in-research": "In research", "awaiting-review": "Awaiting review", completed: "Completed", cancelled: "Cancelled", failed: "Failed" };

export function TodayWorklist({ items, fixtureNotice }: { items: TodayResearchItem[]; fixtureNotice: string }) {
  const [filter, setFilter] = useState<ResearchStatus | "all">("all");
  const visibleSections = sections.filter((section) => filter === "all" || section.status === filter);
  const count = (status: ResearchStatus) => items.filter((item) => item.status === status).length;
  return <><div className="page-title"><div><p>RESEARCH OPERATING SYSTEM</p><h1>Today</h1><span>Prioritize what needs an analyst decision.</span><small className="fixture-notice">{fixtureNotice}</small></div><div><button className="outline" type="button">Customize view</button><Link className="blue-button" href="/new-research"><Plus size={17} />New research</Link></div></div><div className="atlas-tabs" role="tablist" aria-label="Research status"><FilterButton selected={filter === "all"} onClick={() => setFilter("all")}>All <b>{items.length}</b></FilterButton>{sections.map((section) => <FilterButton key={section.status} selected={filter === section.status} onClick={() => setFilter(section.status)}>{section.title} <b>{count(section.status)}</b></FilterButton>)}<FilterButton selected={filter === "completed"} onClick={() => setFilter("completed")}>Completed <b>8</b></FilterButton></div>{filter === "completed" && <div className="empty-state"><b>No completed items in this active queue</b><span>Completed mock research is summarized in the Today overview.</span></div>}{visibleSections.map((section) => <ResearchGroup key={section.status} title={section.title} tone={section.tone} rows={items.filter((item) => item.status === section.status)} />)}</>;
}
function FilterButton({ selected, onClick, children }: { selected: boolean; onClick: () => void; children: React.ReactNode }) { return <button type="button" role="tab" aria-selected={selected} className={selected ? "selected" : ""} onClick={onClick}>{children}</button>; }
function ResearchGroup({ title, tone, rows }: { title: string; tone: string; rows: TodayResearchItem[] }) { return <section className="research-group"><h2><i className={tone} />{title}<b>{rows.length}</b></h2><div className="row header" aria-hidden="true"><span>Company</span><span>Why now</span><span>Current status</span><span>AI completed</span><span>Open question</span><span>Priority</span><span>Action</span></div>{rows.map((item) => <div className="row" key={item.id}><span className="company"><i /><b>{item.company.name}</b><small>{item.company.ticker}</small></span><span>{item.question}</span><span><em className={`pill ${item.status}`}>{labels[item.status]}</em></span><span>{item.completedWork}</span><span>{item.openQuestion}</span><span className="priority">{item.priority === "high" ? "High" : "Med"}</span><Link className="link-button" href={`/research/${item.id}`}>{item.status === "in-research" ? "View progress" : item.status === "awaiting-review" ? "Review" : "Continue"}</Link></div>)}</section>; }
