from pydantic import BaseModel, Field
from typing import List, Optional

class StockDataPayload(BaseModel):
    """Payload received from Java Gateway containing raw stock data."""
    stock_code: str
    price: float
    news: List[str] = []
    # Can extend with more technical/financial indicators as needed

class ComprehensiveReport(BaseModel):
    """The final structured analysis report generated by the LangGraph agents."""
    stock_code: str
    executive_summary: str
    investment_thesis: str
    catalysts: List[str]
    risk_factors: List[str]
    conclusion: str
    advice: str # BUY, SELL, HOLD
    confidence: int

class SignalRecord(BaseModel):
    """Used for backtesting input."""
    id: str
    symbol: str
    direction: str
    entry_price: float
    confidence: int
    created_at: str

class BacktestResult(BaseModel):
    """Output summary of backtest calculations."""
    total_signals: int
    hit_rate_pct: float
    avg_return_pct: float
    status: str # ACTIVE, DOWNWEIGHT, RETIRED
    weight: float
    
class HistoricalCaseDto(BaseModel):
    id: str
    stock_code: str
    title: str
    description: str
    analysis: str
    actual_impact: str
    occurred_at: str

class RerankRequest(BaseModel):
    query: str
    candidates: List[HistoricalCaseDto]
    top_k: int = 3
