"use client";

import { AlertTriangle, ArrowRight, BellRing, Check, Circle, Plus, Save, Sparkles, Target } from "lucide-react";
import Link from "next/link";
import { useState } from "react";
import { AppShell } from "@/components/shell/app-shell";
import type { DecisionItem, DecisionWorkspace, StructuredThesis } from "@/domain/research";
import { useDecisionWorkspaceQuery, useUpdateThesisMutation, useUpsertDecisionItemMutation } from "@/queries/use-decision-workspace";

const tabs = [{ href: "/companies/figure", label: "Company Research" }, { href: "/thesis", label: "Thesis" }, { href: "/risks", label: "Risk / Catalyst" }, { href: "/monitor", label: "What to Monitor" }];

function Frame({ active, children, data }: { active: string; children: React.ReactNode; data: DecisionWorkspace }) { return <AppShell context={<DecisionContext data={data} />}><header className="decision-header"><div><p>DECISION INTELLIGENCE · FIGURE</p><h1>{active}</h1><small>{data.fixtureNotice}</small></div><nav aria-label="Decision workspaces">{tabs.map((tab) => <Link className={tab.label === active ? "active" : ""} href={tab.href} key={tab.href}>{tab.label}</Link>)}</nav></header>{children}</AppShell>; }
function LoadDecision({ children }: { children: (data: DecisionWorkspace) => React.ReactNode }) { const query = useDecisionWorkspaceQuery(); if (query.isPending) return <AppShell context={<div className="skeleton-stack compact"><i /><i /></div>}><div className="skeleton-stack"><i /><i /><i /></div></AppShell>; if (query.isError) return <AppShell context={<div />}><div className="error-state"><b>Decision workspace could not be loaded</b><span>{query.error.message}</span><button type="button" onClick={() => query.refetch()}>Try again</button></div></AppShell>; return children(query.data); }

export function CompanyResearchWorkspace() { return <LoadDecision>{(data) => <Frame active="Company Research" data={data}><section className="company-thesis"><div><small>CURRENT THESIS · {data.currentThesis.status}</small><h2>{data.currentThesis.statement}</h2></div><Link href="/thesis" className="link-button">Open Thesis Workspace <ArrowRight size={13} /></Link></section><div className="decision-two-column"><main><section className="decision-panel"><header><div><small>WHAT CHANGED · PAST 30 DAYS</small><h2>Material company signals</h2></div></header>{data.whatChanged.map((change) => <article className="change-row" key={change.id}><time>{change.date.slice(5)}</time><span className={`materiality ${change.materiality}`}>{change.materiality}</span><div><b>{change.kind}</b><p>{change.summary}</p></div></article>)}</section><div className="company-section-grid">{data.companySections.map((section) => <section className="company-section" key={section.id}><header><h3>{section.title}</h3><span>{section.evidenceCount} evidence</span></header><p>{section.summary}</p><ul>{section.signals.map((signal) => <li key={signal}>{signal}</li>)}</ul></section>)}</div></main><aside className="decision-panel coverage-panel"><header><div><small>EVIDENCE COVERAGE</small><h2>Research depth</h2></div></header>{data.evidenceCoverage.map((coverage) => <div className="coverage-row" key={coverage.label}><span>{coverage.label}</span><i><em style={{ width: `${coverage.value}%` }} /></i><b>{coverage.value}%</b></div>)}<p>Coverage is mock research completeness, not model certainty.</p></aside></div></Frame>}</LoadDecision>; }

export function ThesisWorkspace() { return <LoadDecision>{(data) => <ThesisLoaded data={data} />}</LoadDecision>; }
function ThesisLoaded({ data }: { data: DecisionWorkspace }) { const update = useUpdateThesisMutation(); const [draft, setDraft] = useState<StructuredThesis>(data.currentThesis); return <Frame active="Thesis" data={data}><section className="thesis-toolbar"><span className={`thesis-state ${draft.status}`}>{draft.status}</span><select value={draft.status} onChange={(event) => setDraft({ ...draft, status: event.target.value as StructuredThesis["status"] })} aria-label="Thesis status"><option value="draft">Draft</option><option value="active">Active</option><option value="challenged">Challenged</option><option value="approved">Approved</option></select><button className="blue-button" type="button" onClick={() => update.mutate({ ...draft, updatedAt: new Date().toISOString() })}><Save size={14} />{update.isPending ? "Saving…" : "Save thesis"}</button></section><section className="decision-panel thesis-statement"><header><div><small>CURRENT THESIS</small><h2>Structured investment view</h2></div></header><textarea rows={5} value={draft.statement} onChange={(event) => setDraft({ ...draft, statement: event.target.value })} /></section><div className="thesis-grid"><section className="decision-panel"><header><div><small>KEY ASSUMPTIONS</small><h2>What must remain true</h2></div></header>{draft.assumptions.map((assumption) => <div className="assumption-row" key={assumption.id}><select value={assumption.status} onChange={(event) => setDraft({ ...draft, assumptions: draft.assumptions.map((item) => item.id === assumption.id ? { ...item, status: event.target.value as typeof assumption.status } : item) })}><option value="supported">Supported</option><option value="uncertain">Uncertain</option><option value="challenged">Challenged</option></select><input value={assumption.statement} onChange={(event) => setDraft({ ...draft, assumptions: draft.assumptions.map((item) => item.id === assumption.id ? { ...item, statement: event.target.value } : item) })} /></div>)}</section><section className="decision-panel"><header><div><small>DISCONFIRMING CONDITIONS</small><h2>When the thesis is wrong</h2></div></header>{draft.disconfirmingConditions.map((condition) => <label className={condition.triggered ? "condition triggered" : "condition"} key={condition.id}><input type="checkbox" checked={condition.triggered} onChange={() => setDraft({ ...draft, disconfirmingConditions: draft.disconfirmingConditions.map((item) => item.id === condition.id ? { ...item, triggered: !item.triggered } : item) })} /><span>{condition.triggered ? <AlertTriangle size={15} /> : <Circle size={13} />}{condition.statement}</span></label>)}</section></div><div className="thesis-evidence-links"><Link href="/evidence"><Check size={14} />{draft.supportingEvidenceIds.length} supporting evidence</Link><Link href="/evidence"><AlertTriangle size={14} />{draft.counterEvidenceIds.length} counter evidence</Link></div></Frame>; }

export function RiskCatalystWorkspace() { return <LoadDecision>{(data) => <DecisionItemsLoaded data={data} active="Risk / Catalyst" kinds={["risk", "catalyst"]} />}</LoadDecision>; }
export function MonitorWorkspace() { return <LoadDecision>{(data) => <DecisionItemsLoaded data={data} active="What to Monitor" kinds={["monitor"]} />}</LoadDecision>; }
function DecisionItemsLoaded({ data, active, kinds }: { data: DecisionWorkspace; active: string; kinds: DecisionItem["kind"][] }) { const mutation = useUpsertDecisionItemMutation(); const items = data.decisionItems.filter((item) => kinds.includes(item.kind)); const [newTitle, setNewTitle] = useState(""); function add() { if (newTitle.trim().length < 3) return; mutation.mutate({ id: `mock-${Date.now()}`, kind: kinds[0], category: kinds[0] === "monitor" ? "Analyst Added" : kinds[0] === "risk" ? "New Risk" : "New Catalyst", title: newTitle, detail: "Analyst-added mock item. Edit status and importance as research evolves.", status: kinds[0] === "monitor" ? "watching" : "active", importance: "medium", evidenceIds: [] }); setNewTitle(""); } return <Frame active={active} data={data}><section className="add-decision-item"><div>{active === "What to Monitor" ? <BellRing size={18} /> : <Target size={18} />}<input value={newTitle} onChange={(event) => setNewTitle(event.target.value)} placeholder={active === "What to Monitor" ? "Add a signal to monitor" : "Add a risk"} onKeyDown={(event) => { if (event.key === "Enter") add(); }} /></div><button type="button" className="blue-button" onClick={add} disabled={newTitle.trim().length < 3}><Plus size={14} />Add</button></section>{kinds.map((kind) => <section className="decision-panel item-section" key={kind}><header><div><small>{kind === "risk" ? "DOWNSIDE CONDITIONS" : kind === "catalyst" ? "THESIS CATALYSTS" : "ONGOING SIGNALS"}</small><h2>{kind === "risk" ? "Risks" : kind === "catalyst" ? "Catalysts" : "What to monitor next"}</h2></div><b>{items.filter((item) => item.kind === kind).length}</b></header><div className="decision-item-grid">{items.filter((item) => item.kind === kind).map((item) => <article className={`decision-item ${item.status}`} key={item.id}><div><span className={`importance ${item.importance}`}>{item.importance}</span><small>{item.category}</small></div><h3>{item.title}</h3><p>{item.detail}</p><footer><select value={item.status} onChange={(event) => mutation.mutate({ ...item, status: event.target.value as DecisionItem["status"] })}><option value="active">Active</option><option value="watching">Watching</option><option value="triggered">Triggered</option><option value="resolved">Resolved</option></select><select value={item.importance} onChange={(event) => mutation.mutate({ ...item, importance: event.target.value as DecisionItem["importance"] })}><option value="high">High</option><option value="medium">Medium</option><option value="low">Low</option></select><span>{item.evidenceIds.length} evidence</span></footer></article>)}</div></section>)}</Frame>; }

function DecisionContext({ data }: { data: DecisionWorkspace }) { const risks = data.decisionItems.filter((item) => item.kind === "risk" && item.status !== "resolved"); return <><div className="context-heading"><b>{data.company.name}</b><span>{data.company.ticker}</span></div><div className="context-summary"><small>THESIS STATUS</small><b>{data.currentThesis.status}</b><small>ACTIVE RISKS</small><b>{risks.length}</b><small>CATALYSTS</small><b>{data.decisionItems.filter((item) => item.kind === "catalyst").length}</b><small>MONITOR SIGNALS</small><b>{data.decisionItems.filter((item) => item.kind === "monitor").length}</b></div><p className="context-note"><Sparkles size={13} /> Decision workspaces preserve evidence links and explicit disconfirming conditions.</p></>; }
