server:
  port: ${MCP_SERVER_PORT:7070}

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      pool-name: DataSourceHikariCP
      connection-timeout: 30000
      minimum-idle: 10
      maximum-pool-size: 50
      auto-commit: true
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-test-query: SELECT 1

app:
  security:
    enabled: ${APP_SECURITY_ENABLED:true}
    api-key-header: ${APP_SECURITY_API_KEY_HEADER:X-API-KEY}
    api-key: ${APP_SECURITY_API_KEY}

management:
  endpoint:
    health:
      show-details: never
